#!/bin/bash
# Reflexio Multi-Agent tmux Session Setup (Single Window - All Panes Visible)
# Usage: bash .agent/scripts/setup-tmux.sh [developer_count]
#
# All agents are displayed in a single tiled window so you can watch
# them communicate in real time.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
AGENT_DIR="${PROJECT_ROOT}/.agent"
ROLES_DIR="${AGENT_DIR}/roles"
MESSAGES_DIR="${AGENT_DIR}/messages"
BOARD_FILE="${AGENT_DIR}/board.md"
COMMON_PROTOCOL="${ROLES_DIR}/_common.md"
SESSION_NAME="reflexio-agents"
DEV_COUNT="${1:-5}"
WINDOW_NAME="AGENTS"

echo "================================================"
echo " Reflexio Multi-Agent System セットアップ"
echo "================================================"
echo " プロジェクト: ${PROJECT_ROOT}"
echo " DEV数: ${DEV_COUNT}"
echo ""

# --- Pre-flight checks ---
command -v tmux >/dev/null 2>&1 || { echo "[ERROR] tmux が見つかりません。sudo apt install tmux で導入してください"; exit 1; }
command -v claude >/dev/null 2>&1 || { echo "[ERROR] claude CLI が見つかりません"; exit 1; }

if tmux has-session -t "${SESSION_NAME}" 2>/dev/null; then
    echo "[setup] 既存セッション '${SESSION_NAME}' を終了します"
    tmux kill-session -t "${SESSION_NAME}"
fi

mkdir -p "${MESSAGES_DIR}"

# Initialize board if missing
if [ ! -f "${BOARD_FILE}" ]; then
    cat > "${BOARD_FILE}" << 'BOARD_EOF'
# Agent Message Board

このファイルはエージェント間メッセージの通知ログです。
新しいメッセージを送信したら、このファイルの末尾に1行追加してください。

## メッセージログ

| timestamp | id | from | to | type | subject | status |
|---|---|---|---|---|---|---|
BOARD_EOF
fi

# --- Build system prompt from role file + common protocol ---
build_prompt() {
    local agent_id="$1"
    local role_file="$2"

    local role_content
    role_content=$(<"${role_file}")

    local common_content
    common_content=$(<"${COMMON_PROTOCOL}")

    # Replace {AGENT_ID} placeholder (for DEV template)
    role_content="${role_content//\{AGENT_ID\}/${agent_id}}"

    # Append common protocol
    echo "${role_content}"
    echo ""
    echo "---"
    echo "以下の共通通信プロトコルに従ってください:"
    echo ""
    echo "${common_content}"
}

# --- Start Claude Code in a specific pane ---
# send-keys and Enter are separate calls to ensure proper execution
start_agent() {
    local target="$1"
    local agent_id="$2"
    local role_file="$3"

    echo "[setup] ${agent_id} を起動中... (${target})"

    # Set pane title for visual identification
    tmux select-pane -t "${target}" -T "${agent_id}"

    # Build prompt and write to temp file (avoids shell escaping issues)
    local prompt_file="${AGENT_DIR}/.tmp_prompt_${agent_id}"
    build_prompt "${agent_id}" "${role_file}" > "${prompt_file}"

    # Start claude with system prompt (text and Enter separated)
    tmux send-keys -t "${target}" \
        "claude --system-prompt \"\$(cat '${prompt_file}')\" --allowedTools 'Bash Read Write Edit Glob Grep' --dangerously-skip-permissions"
    sleep 0.5
    tmux send-keys -t "${target}" Enter

    sleep 2

    # Send initial instruction (text and Enter separated)
    tmux send-keys -t "${target}" \
        "あなたは ${agent_id} です。ロール定義を確認しました。.agent/board.md を確認し、自分宛の unread メッセージがあれば読んでください。なければメッセージを待機してください。"
    sleep 0.5
    tmux send-keys -t "${target}" Enter
}

# ======================================================================
# Create tmux session — single window with all panes (tiled layout)
# ======================================================================
echo "[setup] tmux セッションを作成中..."

# Pane assignment:
#   0: PM, 1: PL, 2..(DEV_COUNT+1): DEV1..DEVN,
#   DEV_COUNT+2: LIBRARIAN, DEV_COUNT+3: TESTER, DEV_COUNT+4: REVIEWER,
#   DEV_COUNT+5: WATCHER
TOTAL_PANES=$((DEV_COUNT + 6))  # PM + PL + DEVs + LIB + TST + REV + WATCHER

# Create session (pane 0 is created automatically)
tmux new-session -d -s "${SESSION_NAME}" -n "${WINDOW_NAME}" -c "${PROJECT_ROOT}"

# Create remaining panes
for ((p=1; p<TOTAL_PANES; p++)); do
    tmux split-window -t "${SESSION_NAME}:${WINDOW_NAME}" -c "${PROJECT_ROOT}"
    tmux select-layout -t "${SESSION_NAME}:${WINDOW_NAME}" tiled
done

# Enable pane border titles so each agent is labeled
tmux set-option -t "${SESSION_NAME}" pane-border-status top
tmux set-option -t "${SESSION_NAME}" pane-border-format " #{pane_title} "

echo "[setup] ${TOTAL_PANES} ペイン作成完了 (tiled レイアウト)"

# --- Compute pane indices ---
PANE_PM=0
PANE_PL=1
# DEV panes: indices 2 .. (DEV_COUNT+1)
PANE_LIB=$((DEV_COUNT + 2))
PANE_TST=$((DEV_COUNT + 3))
PANE_REV=$((DEV_COUNT + 4))
PANE_WATCHER=$((DEV_COUNT + 5))

# --- Write pane mapping file for watcher.sh ---
PANE_MAP_FILE="${AGENT_DIR}/.pane_map.sh"
cat > "${PANE_MAP_FILE}" << MAPEOF
# Auto-generated by setup-tmux.sh — do not edit manually
declare -A AGENT_PANES=(
    ["PM"]="${WINDOW_NAME}.${PANE_PM}"
    ["PL"]="${WINDOW_NAME}.${PANE_PL}"
MAPEOF

for ((d=1; d<=DEV_COUNT; d++)); do
    pane_idx=$((d + 1))
    echo "    [\"DEV${d}\"]=\"${WINDOW_NAME}.${pane_idx}\"" >> "${PANE_MAP_FILE}"
done

cat >> "${PANE_MAP_FILE}" << MAPEOF
    ["LIBRARIAN"]="${WINDOW_NAME}.${PANE_LIB}"
    ["TESTER"]="${WINDOW_NAME}.${PANE_TST}"
    ["REVIEWER"]="${WINDOW_NAME}.${PANE_REV}"
)
MAPEOF

echo "[setup] ペインマッピング書き出し完了"

# ======================================================================
# Start agents in their panes
# ======================================================================

# PM & PL
start_agent "${SESSION_NAME}:${WINDOW_NAME}.${PANE_PM}" "PM" "${ROLES_DIR}/PM.md"
start_agent "${SESSION_NAME}:${WINDOW_NAME}.${PANE_PL}" "PL" "${ROLES_DIR}/PL.md"

# DEVs
for ((d=1; d<=DEV_COUNT; d++)); do
    pane_idx=$((d + 1))
    start_agent "${SESSION_NAME}:${WINDOW_NAME}.${pane_idx}" "DEV${d}" "${ROLES_DIR}/DEV.md"
done

# LIBRARIAN, TESTER, REVIEWER
start_agent "${SESSION_NAME}:${WINDOW_NAME}.${PANE_LIB}" "LIBRARIAN" "${ROLES_DIR}/LIBRARIAN.md"
start_agent "${SESSION_NAME}:${WINDOW_NAME}.${PANE_TST}" "TESTER" "${ROLES_DIR}/TESTER.md"
start_agent "${SESSION_NAME}:${WINDOW_NAME}.${PANE_REV}" "REVIEWER" "${ROLES_DIR}/REVIEWER.md"

# WATCHER (label + start script)
tmux select-pane -t "${SESSION_NAME}:${WINDOW_NAME}.${PANE_WATCHER}" -T "WATCHER"
tmux send-keys -t "${SESSION_NAME}:${WINDOW_NAME}.${PANE_WATCHER}" \
    "bash '${AGENT_DIR}/scripts/watcher.sh'"
sleep 0.5
tmux send-keys -t "${SESSION_NAME}:${WINDOW_NAME}.${PANE_WATCHER}" Enter

# --- Done ---
echo ""
echo "================================================"
echo " 起動完了"
echo "================================================"
echo " セッション: ${SESSION_NAME}"
echo " ウィンドウ: ${WINDOW_NAME} (${TOTAL_PANES} ペイン, tiled レイアウト)"
echo ""
echo " ペイン構成:"
echo "   PM, PL,"
for ((d=1; d<=DEV_COUNT; d++)); do
    printf "   DEV%d," "${d}"
done
echo ""
echo "   LIBRARIAN, TESTER, REVIEWER,"
echo "   WATCHER"
echo ""
echo " 操作:"
echo "   Ctrl+b → o        次のペインに移動"
echo "   Ctrl+b → 矢印     矢印方向のペインに移動"
echo "   Ctrl+b → z        ペインを最大化/復帰 (重要!)"
echo "   Ctrl+b → d        デタッチ"
echo ""
echo " 接続: tmux attach -t ${SESSION_NAME}"
echo " 終了: tmux kill-session -t ${SESSION_NAME}"
echo "================================================"

# Select PM pane so user lands there
tmux select-pane -t "${SESSION_NAME}:${WINDOW_NAME}.${PANE_PM}"

# Attach if interactive
if [ -t 1 ]; then
    tmux attach -t "${SESSION_NAME}"
fi
