#!/bin/bash
# Reflexio Multi-Agent Message Watcher
# Polls board.md and remote/user_to_pm.md for new entries
# and notifies target agents via tmux send-keys

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BOARD_FILE="${PROJECT_ROOT}/.agent/board.md"
REMOTE_FILE="${PROJECT_ROOT}/.agent/remote/user_to_pm.md"
SESSION_NAME="reflexio-agents"
POLL_INTERVAL=1

# Agent ID → tmux pane mapping (generated by setup-tmux.sh)
PANE_MAP_FILE="${PROJECT_ROOT}/.agent/.pane_map.sh"
if [ ! -f "${PANE_MAP_FILE}" ]; then
    echo "[ERROR] ペインマッピングファイルが見つかりません: ${PANE_MAP_FILE}"
    echo "        先に setup-tmux.sh を実行してください"
    exit 1
fi
# shellcheck source=/dev/null
source "${PANE_MAP_FILE}"

# Initialize line counts
LAST_LINE_COUNT=0
if [ -f "${BOARD_FILE}" ]; then
    LAST_LINE_COUNT=$(wc -l < "${BOARD_FILE}")
fi

LAST_REMOTE_LINE_COUNT=0
if [ -f "${REMOTE_FILE}" ]; then
    LAST_REMOTE_LINE_COUNT=$(wc -l < "${REMOTE_FILE}")
fi

echo "================================================"
echo " Reflexio Message Watcher"
echo "================================================"
echo " 監視対象1: ${BOARD_FILE}"
echo " 監視対象2: ${REMOTE_FILE}"
echo " ポーリング間隔: ${POLL_INTERVAL}秒"
echo " 初期行数: board=${LAST_LINE_COUNT}, remote=${LAST_REMOTE_LINE_COUNT}"
echo " 新しいメッセージを監視中..."
echo ""

while true; do
    sleep "${POLL_INTERVAL}"

    [ -f "${BOARD_FILE}" ] || continue

    CURRENT_LINE_COUNT=$(wc -l < "${BOARD_FILE}")

    if [ "${CURRENT_LINE_COUNT}" -gt "${LAST_LINE_COUNT}" ]; then
        NEW_LINES_START=$((LAST_LINE_COUNT + 1))
        NEW_LINES=$(tail -n +"${NEW_LINES_START}" "${BOARD_FILE}")

        while IFS= read -r line; do
            # Skip empty lines, header, separator
            [[ -z "${line}" ]] && continue
            [[ "${line}" == "|---"* ]] && continue
            [[ "${line}" == "| timestamp"* ]] && continue
            [[ "${line}" != "|"* ]] && continue

            # Parse markdown table row: | timestamp | id | from | to | type | subject | status |
            local_id=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $3); print $3}')
            local_from=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $4); print $4}')
            local_to=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $5); print $5}')
            local_subject=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $7); print $7}')

            # Validate
            [[ -z "${local_to}" ]] && continue
            [[ "${local_to}" == "to" ]] && continue

            echo "[$(date '+%H:%M:%S')] 新メッセージ: ${local_id} (${local_from} → ${local_to})"

            # Look up tmux pane target (e.g. "PM-PL.0")
            local_pane="${AGENT_PANES[${local_to}]:-}"
            if [ -z "${local_pane}" ]; then
                echo "  WARNING: 不明なエージェント '${local_to}' - スキップ"
                continue
            fi

            # Extract window name from pane target (e.g. "PM-PL" from "PM-PL.0")
            local_window="${local_pane%%.*}"

            # Check window exists
            if ! tmux list-windows -t "${SESSION_NAME}" -F '#{window_name}' 2>/dev/null | grep -q "^${local_window}$"; then
                echo "  WARNING: ウィンドウ '${local_window}' が見つかりません - スキップ"
                continue
            fi

            # Send notification via tmux send-keys to the specific pane (Enter separated)
            NOTIFICATION="[MESSAGE] ${local_id} を読んでください。ファイル: .agent/messages/${local_id}.yaml (送信元: ${local_from}, 件名: ${local_subject})"
            tmux send-keys -t "${SESSION_NAME}:${local_pane}" "${NOTIFICATION}"
            sleep 0.5
            tmux send-keys -t "${SESSION_NAME}:${local_pane}" Enter

            echo "  → ${local_to} に通知送信完了"

        done <<< "${NEW_LINES}"

        LAST_LINE_COUNT="${CURRENT_LINE_COUNT}"
    fi

    # --- Remote instruction file monitoring (user_to_pm.md) ---
    [ -f "${REMOTE_FILE}" ] || continue

    CURRENT_REMOTE_LINE_COUNT=$(wc -l < "${REMOTE_FILE}")

    if [ "${CURRENT_REMOTE_LINE_COUNT}" -gt "${LAST_REMOTE_LINE_COUNT}" ]; then
        NEW_REMOTE_START=$((LAST_REMOTE_LINE_COUNT + 1))
        NEW_REMOTE_LINES=$(tail -n +"${NEW_REMOTE_START}" "${REMOTE_FILE}")

        while IFS= read -r line; do
            # Skip empty lines, header, separator
            [[ -z "${line}" ]] && continue
            [[ "${line}" == "|---"* ]] && continue
            [[ "${line}" == "| id"* ]] && continue
            [[ "${line}" != "|"* ]] && continue

            # Parse: | id | timestamp | subject | status |
            remote_id=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}')
            remote_subject=$(echo "${line}" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $4); print $4}')

            [[ -z "${remote_id}" ]] && continue
            [[ "${remote_id}" == "id" ]] && continue

            echo "[$(date '+%H:%M:%S')] リモート指示: ${remote_id} (USER → PM)"

            # Send to PM pane
            local_pane="${AGENT_PANES[PM]:-}"
            if [ -z "${local_pane}" ]; then
                echo "  WARNING: PMペインが見つかりません - スキップ"
                continue
            fi

            local_window="${local_pane%%.*}"
            if ! tmux list-windows -t "${SESSION_NAME}" -F '#{window_name}' 2>/dev/null | grep -q "^${local_window}$"; then
                echo "  WARNING: ウィンドウ '${local_window}' が見つかりません - スキップ"
                continue
            fi

            NOTIFICATION="[REMOTE] ${remote_id} を読んでください。ファイル: .agent/messages/${remote_id}.yaml (送信元: USER, 件名: ${remote_subject})"
            tmux send-keys -t "${SESSION_NAME}:${local_pane}" "${NOTIFICATION}"
            sleep 0.5
            tmux send-keys -t "${SESSION_NAME}:${local_pane}" Enter

            echo "  → PM に通知送信完了"

        done <<< "${NEW_REMOTE_LINES}"

        LAST_REMOTE_LINE_COUNT="${CURRENT_REMOTE_LINE_COUNT}"
    fi
done
